create table if not exists public.localities (
  id bigint generated by default as identity primary key,
  locality text unique not null,
  district text not null,
  pincode text not null,
  state text not null,
  rep_lat double precision not null check (rep_lat between -90 and 90),
  rep_lon double precision not null check (rep_lon between -180 and 180),
  apartment_count integer not null default 0 check (apartment_count >= 0)
);

create table if not exists public.apartments (
  id bigint generated by default as identity primary key,
  name text not null,
  locality text not null references public.localities(locality) on update cascade,
  lat double precision not null check (lat between -90 and 90),
  lon double precision not null check (lon between -180 and 180),
  coordinate_quality text not null default 'exact',
  unique (name, locality)
);

create table if not exists public.transit_pois (
  id text primary key,
  type text not null check (type in ('metro', 'bus', 'railway', 'taxi')),
  name text not null,
  lat double precision not null check (lat between -90 and 90),
  lon double precision not null check (lon between -180 and 180),
  fetched_at timestamptz not null default now()
);

create index if not exists apartments_locality_idx on public.apartments(locality);
create index if not exists apartments_name_idx on public.apartments(lower(name));
create index if not exists transit_pois_type_fetched_idx on public.transit_pois(type, fetched_at desc);

alter table public.localities enable row level security;
alter table public.apartments enable row level security;
alter table public.transit_pois enable row level security;

drop policy if exists "public read localities" on public.localities;
drop policy if exists "public read apartments" on public.apartments;
drop policy if exists "public read transit" on public.transit_pois;
create policy "public read localities" on public.localities for select to anon, authenticated using (true);
create policy "public read apartments" on public.apartments for select to anon, authenticated using (true);
create policy "public read transit" on public.transit_pois for select to anon, authenticated using (true);

revoke insert, update, delete on public.localities from anon, authenticated;
revoke insert, update, delete on public.apartments from anon, authenticated;
revoke insert, update, delete on public.transit_pois from anon, authenticated;
grant select on public.localities, public.apartments, public.transit_pois to anon, authenticated;
