create table if not exists localities (id bigint generated by default as identity primary key, locality text unique not null, district text not null, pincode text not null, state text not null, rep_lat double precision not null, rep_lon double precision not null, apartment_count integer default 0);
create table if not exists apartments (id bigint generated by default as identity primary key, name text not null, locality text not null references localities(locality), lat double precision not null, lon double precision not null, coordinate_quality text default 'exact');
create table if not exists transit_pois (id text primary key, type text not null, name text, lat double precision not null, lon double precision not null, fetched_at timestamptz default now());
alter table localities enable row level security; alter table apartments enable row level security; alter table transit_pois enable row level security;
create policy "public read localities" on localities for select using (true);
create policy "public read apartments" on apartments for select using (true);
create policy "public read transit" on transit_pois for select using (true);
