'use client';
import {useEffect,useState} from 'react';
import L from 'leaflet';
import {CircleMarker,MapContainer,Marker,Popup,TileLayer,Tooltip,useMap} from 'react-leaflet';
import {apartments,localities} from '@/lib/data';
import {haversineKm} from '@/lib/geo';
import type {Apartment,Locality,TransitPoi,TransitType} from '@/lib/types';
const bounds:L.LatLngBoundsExpression=[[12.7,77.2],[13.35,77.9]],colors:Record<TransitType,string>={metro:'#7c3aed',bus:'#16a34a',railway:'#dc2626',taxi:'#d97706'};
function icon(color:string){return L.divIcon({className:'',html:`<span style="display:block;width:14px;height:14px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:${color};border:2px solid white;box-shadow:0 2px 5px #0005"></span>`,iconSize:[18,18],iconAnchor:[7,14]})}
function Controller({selected,apartment}:{selected:Locality|null;apartment:Apartment|null}){const map=useMap();useEffect(()=>{if(apartment)map.flyTo([apartment.lat,apartment.lon],16,{duration:.7});else if(selected)map.flyTo([selected.rep_lat,selected.rep_lon],13,{duration:.6});else map.fitBounds(bounds,{padding:[18,18]})},[map,selected,apartment]);return null}
function ZoomLabels(){const map=useMap(),[zoom,setZoom]=useState(map.getZoom());useEffect(()=>{const fn=()=>setZoom(map.getZoom());map.on('zoomend',fn);return()=>{map.off('zoomend',fn)}},[map]);return <>{zoom>=13&&localities.map(l=><Marker key={l.id} position={[l.rep_lat,l.rep_lon]} interactive={false} icon={L.divIcon({className:'',html:`<span class="pincode-label">${l.locality} · ${l.pincode}</span>`,iconAnchor:[45,-12]})}/>)}{zoom>=16&&apartments.map(a=><Marker key={a.id} position={[a.lat,a.lon]} icon={icon('#0f766e')}><Popup><strong>{a.name}</strong><br/>{a.locality}</Popup></Marker>)}</>}
export default function GeoMap({selected,focusedApartment,adjacent,onSelect,activeTransit,pois}:{selected:Locality|null;focusedApartment:Apartment|null;adjacent:Locality[];onSelect:(l:Locality)=>void;activeTransit:Set<TransitType>;pois:Record<string,TransitPoi[]>}){const adjacentIds=new Set(adjacent.map(a=>a.id));return <MapContainer bounds={bounds} zoomControl preferCanvas><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png"/><Controller selected={selected} apartment={focusedApartment}/>{localities.map(l=>{const isSelected=l.id===selected?.id,isAdjacent=adjacentIds.has(l.id);return <CircleMarker key={l.id} center={[l.rep_lat,l.rep_lon]} radius={isSelected?12:isAdjacent?10:8} pathOptions={{color:isSelected?'#1d4ed8':isAdjacent?'#ea580c':'#1e3a5f',weight:isSelected?4:isAdjacent?3:2,fillColor:isSelected?'#3b82f6':'#1e3a5f',fillOpacity:isAdjacent?.12:.78}} eventHandlers={{click:()=>onSelect(l)}}><Tooltip direction="top"><strong>{l.locality}</strong><br/>{l.pincode} · {l.apartment_count} apartments</Tooltip></CircleMarker>})}{Array.from(activeTransit).flatMap(type=>(pois[type]??[]).map(p=><Marker key={p.id} position={[p.lat,p.lon]} icon={icon(colors[type])}><Popup><strong>{p.name}</strong><br/>{type}{selected&&<><br/>{haversineKm(selected.rep_lat,selected.rep_lon,p.lat,p.lon).toFixed(1)} km from {selected.locality}</>}</Popup></Marker>))}<ZoomLabels/></MapContainer>}
